name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            artifact: linux-bb-bj-p2-x86-64

          - os: windows-2022
            artifact: win-bb-bj-p2-dll-x86-64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Linux dependencies
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libmodplug-dev

      # Windows dependencies
      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            make
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-libmodplug

      - name: Build Linux
        if: runner.os == 'Linux'
        run: make

      - name: Build Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/

release:
  if: startsWith(github.ref, 'refs/tags/')
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-assets

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-assets/**/*
