name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux_x86_64

          - os: windows-latest
            artifact: win_x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Linux dependencies
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libmodplug-dev

      # Windows dependencies
      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            make
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-libmodplug

      - name: Build Linux
        if: runner.os == 'Linux'
        run: make

      - name: Build Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/
